apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: vigo-qlik-menu-frontend
  name: vigo-qlik-menu-frontend
spec:
  ports:
    - name: "80"
      port: 80
  type: LoadBalancer
  selector:
    io.kompose.service: vigo-qlik-menu-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: vigo-qlik-menu-frontend
  name: vigo-qlik-menu-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: vigo-qlik-menu-frontend
  template:
    metadata:
      labels:
        io.kompose.service: vigo-qlik-menu-frontend
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabs.azurecr.io/vigo-qlik-menu-frontend:build.${BUILD_NUMBER}
          name: vigo-qlik-menu-frontend
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Europe/Oslo
