apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/ingress/routes/0/host"
        value: "analyse.novari.no"
      - op: replace
        path: "/spec/ingress/routes/0/path"
        value: "/"
    target:
      kind: Application
      name: novari-analyse-menu-frontend
